package util

import (
	"bufio"
	"bytes"

	"sigs.k8s.io/yaml"
)

const YamlContentHeader string = "# DO NOT MODIFY! This file was generated by the Riser platform. Changes will be lost\n"

// ToYaml serializes to pretty YAML with JSON tags using the k8s encoding packages for consistency
func ToYaml(in interface{}) ([]byte, error) {
	jsonData, err := yaml.Marshal(in)
	if err != nil {
		return nil, err
	}
	yamlData, err := yaml.JSONToYAML(jsonData)
	if err != nil {
		return nil, err
	}
	buffer := &bytes.Buffer{}
	writer := bufio.NewWriter(buffer)
	_, err = writer.WriteString(YamlContentHeader)
	if err != nil {
		return nil, err
	}
	_, err = writer.Write(yamlData)
	if err != nil {
		return nil, err
	}
	err = writer.Flush()
	if err != nil {
		return nil, err
	}
	return buffer.Bytes(), nil
}

// ParseYaml deserializes YAML into a struct with JSON tags.
func ParseYaml(in []byte, out interface{}) error {
	return yaml.UnmarshalStrict(in, out)
}
